# Generated by Django 5.2.1 on 2025-06-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_constraint_lesson_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSubGroup',
            new_name='StudentGroup',
        ),
    ]
